### ISSUE TITLE
Switch between umv and mv command 

### ISSUE THREAD

**Issue by dschick** [MBI-Div-B/sardana-bookmarks#1]
Right now the command for a move is hard cided as umv. In order to make the macro class more generic, one could make this configurable, or even save it with in the bookmark. I guess for some people umv might be a problem and they prefer mv instead. 
There could be also other commands involved such as ubr or br.
But this could of course blow up the thing quite a bit.

**Comment by dscran** [comment]
That's a good point. I think having a global switch for which coordinate space to use (user, dial, ?) is easy to implement without introducing much overhead. I would refrain from having this for each single bookmark though - I think that would be quite error-prone.
For the hkl movement: I haven't worked with that. Would a bookmark for that not just be possible by saving the diffractometer motor positions? Or would those typically be hidden from the user?

**Comment by dschick** [comment]
So Sardana always moves in user positions. The u in umv stands for update not user.
So it is even simpler, than what you where thinking of.
Regarding the ubr: sure you will the underlying motors wuch as tth and th which you can still use, but ubr and br also take the energy into acount so you can be at the same hkl for to different energies which means two different th2th positions. Thisbisnwhy I would prefer to use the ubr command over the umv command here.
