### ISSUE TITLE
sequential movement output is overwritten

### ISSUE THREAD

**Issue by dschick** [MBI-Div-B/sardana-bookmarks#2]
when moving two motors sequentially, the output of the internally used `umv` macro is overwritten.
Maybe it is better to plot it under each other have a proper history in spock.

**Comment by dscran** [comment]
I agree, that's a little confusing. This happens automatically for some reason - is there a better way than to have another `self.output('')` after each call to the move macro?

**Comment by dschick** [comment]
I think you need to add somehow a linebreak.
There was also some disccusion about that: https://github.com/sardana-org/sardana/issues/1519
