### ISSUE TITLE
Add to sardana-extras catalogue

### ISSUE THREAD

**Issue by reszelaz** [MBI-Div-B/sardana-bookmarks#6]
Hi MBI team,

Today I was looking for your bookmark project because on one of our beamlines they need something similar. 
To be honest it took me some time to find it and I missed it listed in [sardana-extras](https://gitlab.com/sardana-org/sardana-extras) catalogue. Do you agree to list it there?

Cheers

**Comment by dschick** [comment]
Hi @reszelaz 

Thanks for noticing our laziness :)

We have a lot of tango and sardana controllers and macros which need to be added to the catalog.
I have this on our agenda but of course, you are welcome to add this one also by yourself.

Best

Daniel

**Comment by reszelaz** [comment]
Hi @dschick,
I just added this project to https://gitlab.com/sardana-org/sardana-extras/-/blob/main/plugin/other.md. Thanks for sharing the code with us!
Cheers,
Zibi
